apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-staging
  namespace: {{ .Values.namespace }}
spec:
  secretName: ilem0n-staging-certificate
  issuerRef:
    name: letsencrypt-staging
  dnsNames:
  - ilem0n.de